server:
  port: 20011
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:28888/eureka/
spring:
  application:
    name: redismq-producer
  redis:
    host: your ip
    port: 3311
    database: 66
    password: hjNVy6oTJNECwg
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    timeout: 1000ms